// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pdyeticfozgdjnrvzcrv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBkeWV0aWNmb3pnZGpucnZ6Y3J2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4MjczNTgsImV4cCI6MjA1OTQwMzM1OH0.LzzdqRrBmflQAJ3EqZ0hbv3I2FOsLvEzqhpntxm4MGs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);